
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUJ
 */

public class UpdateStudent extends DBConnect    {

    /**
     * Creates new form AddStudent
     */
    public UpdateStudent() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        chk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 10, 0, 0);
        jPanel1.add(jTextField1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel1.add(jTextField2, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Update Student Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 120, 107, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        jRadioButton1.setText("Name");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 80, 0, 0);
        jPanel1.add(jRadioButton1, gridBagConstraints);

        jRadioButton2.setText("Room");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 80, 0, 0);
        jPanel1.add(jRadioButton2, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Block");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 10, 0, 0);
        jPanel1.add(jLabel15, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "G1", "G2", "G3", "B1","B2","B3" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 25, 0, 0);
        jPanel1.add(jComboBox1, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Floor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel16, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3","4","5" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        jPanel1.add(jComboBox2, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Room No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabel17, gridBagConstraints);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 0, 0);
        jPanel1.add(jComboBox3, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Check Vacancy Status");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 65);
        jPanel1.add(jButton4, gridBagConstraints);

        chk.setText("Get Details");
        chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActionPerformed(evt);
            }
        });
        jPanel1.add(chk, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         //deleting from block table
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, password);
            stmt= con.createStatement();

            String d_studentID=(jTextField1.getText());
            String d_name=(jTextField2.getText());
            String d_block, sql3,sql2;
             
            if(!d_studentID.contains("ST"))    {
               d_studentID="ST_"+d_studentID; 
            }
           
            sql2="select name from studentdb where StudentID = ?";
              ps2=con.prepareStatement(sql2);
              ps2.setString(1,d_studentID);
              rs2=ps2.executeQuery();
              if(!rs2.next()) {
                  JOptionPane.showMessageDialog(null,"No student found with the given details!");
              }
            else{
                 
                        if(jRadioButton1.isSelected())
                        { sql2="UPDATE studentdb SET Name = ? where StudentID = ?";
                          ps2=con.prepareStatement(sql2);
                          ps2.setString(1,d_name);
                          ps2.setString(2,d_studentID);
                          ps2.executeUpdate();
                        } 

                         if(jRadioButton2.isSelected())
                        {   //deleting entry from             
                          int d_RoomNo, d_floor;
                          sql2="select Block, Floor, RoomNo from studentdb where StudentID = ?";
                          ps2=con.prepareStatement(sql2);
                          ps2.setString(1,d_studentID);
                          rs2=ps2.executeQuery();

                              try { if(rs2.next())
                                        {   d_block=(rs2.getString(1));
                                            d_floor =Integer.parseInt(rs2.getString(2));
                                            d_RoomNo=Integer.parseInt(rs2.getString(3));

                                            //further changes

                              int occ;             
                              sql3="select Status, NoOfOccupants from "+d_block+" where Floor= ? and Room = ?";
                              ps3=con.prepareStatement(sql3);
                              ps3.setInt(1,d_floor);
                              ps3.setInt(2,d_RoomNo);
                              rs3=ps3.executeQuery();

                              String sql4, d_status;
                              try {  if(rs3.next())
                                       { if(rs3.getString(2).equals("0")==false)// room not empty
                                          { occ=Integer.parseInt(rs3.getString(2));
                                            occ=occ-1;

                                             d_status="Vacant";                             
                                             sql4="update "+d_block+" set NoOfOccupants = ? , Status= ? where Room = ? and Floor = ?";//
                                             ps4=con.prepareStatement(sql4);
                                             ps4.setInt(1,occ);
                                             ps4.setString(2,d_status);
                                             ps4.setInt(3,d_RoomNo);
                                             ps4.setInt(4,d_floor);
                                             ps4.executeUpdate();
                                          } 
                                        }
                                     } //end of try

                           catch (SQLException ex)
                                     { Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);}  
                                            //further changes end                                   
                                      }
                                  } // end of outer try

                           catch (SQLException ex) { Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
                                                   }  

                   //deletion from block ends

                   //update block info to the new one
                        String d_block1 = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
                        String d_floor1= jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
                        String d_RoomNo1= jComboBox3.getItemAt(jComboBox3.getSelectedIndex());

                        //java.sql.Date sqlDate = new java.sql.Date(now.getTime());
                        sql3="select count(*) from studentdb where Block = ? and Floor = ? and RoomNo = ?";
                        ps3 = con.prepareStatement(sql3);
                        ps3.setString(1,d_block1 );
                        ps3.setString(2,d_floor1 );
                        ps3.setString(3,d_RoomNo1);
                        rs=ps3.executeQuery();

                        try { if(rs.next())
                            // System.out.println(rs.getString(1));
                              if(rs.getString(1).equals("2"))
                               {   System.out.println("room full");
                                   throw new RoomFullException();                    
                               }
                           }
                        catch (SQLException ex) {
                            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);}

                        int occ;
                        sql3="select Status, NoOfOccupants from "+d_block1+" where Floor= ? and Room = ?";
                        //sql="SELECT COUNT(*) FROM "+d_block+" WHERE STATUS= 'Vacant' ";
                        ps3=con.prepareStatement(sql3);
                        ps3.setString(1,d_floor1);
                        ps3.setString(2,d_RoomNo1);
                        rs3=ps3.executeQuery();

                        String sql4, d_status;
                        try { if(rs3.next())
                            { if(rs3.getString(1).equals("Vacant"))
                                {
                                    occ=Integer.parseInt(rs3.getString(2));
                                    occ=occ+1;
                                    System.out.println(occ);

                                    if(occ==2)
                                    d_status="Full";
                                    else
                                    d_status="Vacant";

                                    sql4="update "+d_block1+" set NoOfOccupants = ?, Status= ? where Room = ? and Floor = ?";//
                                    ps4=con.prepareStatement(sql4);
                                    ps4.setInt(1,occ);
                                    ps4.setString(2,d_status);
                                    ps4.setString(3,d_RoomNo1);
                                    ps4.setString(4,d_floor1);
                                    ps4.executeUpdate();
                                }
                            }
                        }

                        catch (SQLException ex) {
                            Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);}

                      String sql="update studentdb set Block=?,Floor=?,RoomNo=? where StudentID = ?";
                        ps = con.prepareStatement(sql);

                        ps.setString(1,d_block1 );
                        ps.setString(2,d_floor1 );
                        ps.setString(3,d_RoomNo1 );
                        ps.setString(4,d_studentID );
                        ps.executeUpdate();
                   //update block info to the new one ends
                        } //jRadioButton2 ends

                             //deleting from studentdb ends

                        JOptionPane.showMessageDialog(null,"Updated Successfully!");
        }
            con.close();

        }
        catch(RoomFullException e)
              { System.out.println(e);
            JOptionPane.showMessageDialog(null, "Room Already Full!","Book another Room!!",
                JOptionPane.ERROR_MESSAGE );  }

        catch(Exception e)
        { 
            
           System.out.println(e);
            JOptionPane.showMessageDialog(null, "Update failed!","Failed!!",
                JOptionPane.ERROR_MESSAGE );  
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     Room_Vacancy rv = new Room_Vacancy();
     rv.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActionPerformed
        // TODO add your handling code here:
           String studID = jTextField1.getText();
                    if(studID.equals(null))  {
                         //message.setText("This feild can't be empty");
                    }
                    else      {
                          if(!studID.contains("ST"))    {
                                studID="ST_"+studID; 
                        }        
                          try   {
                              
                                Class.forName("com.mysql.jdbc.Driver");
	  con = DriverManager.getConnection(url, user, password);
                                String sql="Select name from studentdb where StudentID=?";
                                ps = con.prepareStatement(sql);
                                ps.setString(1,studID);
                                rs = ps.executeQuery(); 
                                
                                if(!rs.next())  {
                                    JOptionPane.showMessageDialog(null,"No student found with the given details!");
                                }
                                
                                else    {
                                    ViewPersonalInfo vpc =new ViewPersonalInfo(studID);
                                        vpc.setVisible(true);
                                }
                          }
                          catch(Exception exc)    {
                              System.out.print("Something wrong happened at our end !");
                          }
                          
                    }
    }//GEN-LAST:event_chkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateStudent us = new UpdateStudent();
             us.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
