
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MUJ
 */
public class ViewStudentdb extends DBConnect {

    /**
     * Creates new form ViewStudentdb
     */
    public static DefaultTableModel model;
    public ViewStudentdb() {
        initComponents();
        
        //starts                       
                            
           String studentID;
        String name="", block="", floor,roomno,dob,gender, email, contactno,address,complaintid, complaintstatus;
       
         try
          { 
            Class.forName("com.mysql.jdbc.Driver");
	    con = DriverManager.getConnection(url, user, password);
            String sql="Select * from studentdb";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
                    int i=0;
                    while(rs.next())
                    {        studentID=rs.getString("StudentID");
                                name=rs.getString("Name");
                                block =rs.getString("Block");
                                floor=rs.getString("Floor");
                                roomno=rs.getString("RoomNo");
                                dob=rs.getString("DateOfBirth");
                                gender=rs.getString("Gender");
                                email=rs.getString("Email");
                                contactno=rs.getString("ContactNo");
                                address=rs.getString("AddressLine1");
                                complaintid=rs.getString("ComplaintID");
                                complaintstatus=rs.getString("ComplaintStatus");

                                model.addRow(new Object[]{studentID,name,block,floor,roomno,dob,gender,email,contactno,address,complaintid,complaintstatus});
                                i++;           
                    }

                    if(i<1)
                    {JOptionPane.showMessageDialog(null,"No Record Found","Error",JOptionPane.ERROR_MESSAGE);}

                    if(i==1)
                    {System.out.println(i+"Record Found");
                     JOptionPane.showMessageDialog(null,i+" Record Found!");}

                    else
                    {System.out.println(i+"Records Found");
                     JOptionPane.showMessageDialog(null,i+" Records Found!");}

                   }  
    
                   
          catch(Exception e)
          {            
              System.out.println(e);
              JOptionPane.showMessageDialog(null, e.getMessage(),"Error",
	     JOptionPane.ERROR_MESSAGE);}
         //ends
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 300));

        model= new javax.swing.table.DefaultTableModel(  new Object [][] {
        },   new String [] {
            "Student ID", "Name", "Block", "Floor","Room No.","Date of Birth","Gender","Email", "Contact No.","Address Line 1","Complaint ID","Complaint Status"
        });
        jTable2.setModel(model);
        jTable2.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentdb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentdb().setVisible(true);
                
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
